// Editorial Signal style: home is a numbered editorial scroll, using asymmetry and signal-orange actions.
import { ArrowDown, ArrowUpRight, Plus } from 'lucide-react';
import { Link } from 'wouter';
import { faqs, plans, projects, services, siteSettings, stats } from '@/data/siteContent';

const SectionLabel = ({ index, label }: { index: string; label: string }) => <div className="section-label"><span>({index})</span><span>{label}</span><span>© {siteSettings.year}</span></div>;
const ButtonLink = ({ href, children }: { href: string; children: React.ReactNode }) => <Link href={href} className="signal-button">{children}<ArrowUpRight size={17} /></Link>;

export default function Home() {
  return <div className="home-page">
    <section className="hero section-pad"><div className="hero-copy"><p className="eyebrow">Independent creative studio / 19°</p><h1>Make the<br /><span>signal</span><br />impossible to miss.</h1><p className="hero-intro">We turn raw ideas into visual systems with a point of view — art direction, photography, and strategy for brands in motion.</p><ButtonLink href="/about">Explore the studio</ButtonLink></div><div className="hero-media"><img src={mediaHero()} alt="" /><div className="hero-caption"><span>01 / 04</span><span>Direction that moves</span></div></div><div className="scroll-cue"><ArrowDown size={16} /> Scroll to explore</div></section>
    <section className="about-strip section-pad"><SectionLabel index="01" label="About us" /><div className="about-grid"><p className="display-copy">Ideas, given <em>somewhere</em> to go.</p><div><p className="body-copy">On The Radar is a part-time creative partner dedicated to your continuous stream of projects. We bring clarity to the in-between: the moment a thought becomes a system, a system becomes a world, and a world starts moving.</p><ButtonLink href="/about">How we work</ButtonLink></div></div><div className="about-foot"><span>(Pre) Igniting ideas with precision and intentional design.</span><span>(+Post) Driven by bold aesthetics and functional simplicity.</span><span>(=Results) <b>15</b> new clients / <b>100%</b> momentum</span></div></section>
    <section className="portfolio-preview section-pad"><SectionLabel index="02" label="Selected work" /><div className="section-heading"><h2>Work that<br /><em>leaves a mark.</em></h2><ButtonLink href="/work/portfolio">See all (07)</ButtonLink></div><div className="project-grid">{projects.map(project => <Link href={`/work/portfolio/${project.slug}`} className="project-card" key={project.id}><div className="project-image"><img src={project.image.src} alt={project.image.alt} loading="lazy" /></div><div className="project-meta"><span>({project.index})</span><div><h3>{project.title}</h3><p>{project.category} <span>© {project.year}</span></p></div><ArrowUpRight size={18} /></div></Link>)}</div></section>
    <section className="services-section section-pad"><SectionLabel index="03" label="Premium services" /><div className="services-intro"><h2>Shape the<br /><em>whole picture.</em></h2><p>One sharp creative partner, from first instinct to final frame.</p></div><div className="service-list">{services.map(service => <article className="service-row" key={service.index}><div className="service-number">{service.index}</div><div className="service-copy"><p className="eyebrow">{service.title}</p><h3>{service.subtitle}</h3><p>{service.description}</p></div><img src={service.image.src} alt={service.image.alt} loading="lazy" /></article>)}</div></section>
    <section className="pricing-section section-pad"><SectionLabel index="04" label="Pricing" /><div className="pricing-intro"><h2>Pick a direction.<br /><em>We’ll shape the system.</em></h2><p>Simple monthly plans for brands that want to keep the work moving.</p></div><div className="plan-grid">{plans.map((plan, i) => <article className={`plan-card ${i === 1 ? 'featured' : ''}`} key={plan.name}><div><p className="eyebrow">0{i + 1} / {plan.name}</p><p className="plan-description">{plan.description}</p></div><div className="price"><small>$</small><strong>{plan.price}</strong><span>/ month</span></div><Link href="/contact" className="plan-link">Join us now <ArrowUpRight size={16} /></Link><div className="includes"><p>What’s included</p>{plan.features.map(feature => <span key={feature}><Plus size={13} />{feature}</span>)}</div></article>)}</div></section>
    <section className="stats-section section-pad"><SectionLabel index="05" label="The measure" /><div className="stats-grid">{stats.map(stat => <article key={stat.label}><strong>{stat.value}</strong><h3>{stat.label}</h3><p>{stat.description}</p></article>)}</div></section>
    <section className="archive-section section-pad"><SectionLabel index="06" label="Archive" /><div className="archive-list">{['Outside', 'Juvede', 'Zaine', 'Wall Out', 'Geaton', 'Skate'].map((item, i) => <div key={item}><span>{i % 2 === 0 ? '2025' : '2024'}</span><h3>{item}</h3><ArrowUpRight size={20} /></div>)}</div><p className="archive-quote">“We are faster, better<br />and <em>clearer.</em>”</p></section>
    <section className="faq-section section-pad"><SectionLabel index="07" label="Frequently asked questions" /><div className="faq-layout"><h2>Clear answers<br /><em>for the next move.</em></h2><div className="faq-list">{faqs.map(item => <details key={item.question}><summary>{item.question}<Plus size={18} /></summary><p>{item.answer}</p></details>)}</div></div></section>
  </div>;
}

function mediaHero() { return '/manus-storage/otr-hero_fa8b9562.jpg'; }
